#############################################
# This is a fixed version of this mod
# https://www.nexusmods.com/nomanssky/mods/1868
#############################################

!inputPakFile NMSARC.Precache.pak

!mbinFile MODELS/COMMON/ROBOTS/SENTINELMECH/ENTITIES/MECHARMOUR.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/COMMON/ROBOTS/FREIGHTERDRONE/ENTITIES/FREIGHTERDRONE.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/COMMON/ROBOTS/WALKER/ENTITIES/WALKER.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SHARKRIG/SHARK/ENTITIES/SHARK1.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPE/ENTITIES/_BODY_ALIEN.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPE/ENTITIES/_BODY_WEIRD.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPE/ENTITIES/_BODY_DEER.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FLYINGSNAKE/FLYINGSNAKE/ENTITIES/_BODY_WORM.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FLYINGSNAKE/FLYINGSNAKE/ENTITIES/KITECREATURE.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SLUG/SLUG/ENTITIES/DATA.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FLYINGLIZARDRIG/FLYINGLIZARD/ENTITIES/BODY_LIZARD.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SMALLBIRD/BIRDFLOCK/ENTITIES/BIRDFLOCK.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SMALLBIRD/BIRD/ENTITIES/SMALLBIRD.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SMALLBIRD/BIRD/ENTITIES/BIRD.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SMALLBIRD/BIRD/ENTITIES/_BODY_BIRD.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/DRILL/ENTITIES/DRILL.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIG/ENTITIES/WEIRDCRYSTAL.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

#!mbinFile MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIG/ENTITIES/WEIRDFLOAT.ENTITY.MBIN
#!include CompanionPetUnlocker_InteractionAction.inc

#!mbinFile MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIG/ENTITIES/WEIRDROLL.ENTITY.MBIN
#!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/GROUNDCREATURE/ENTITIES/_GROUND_RODENT.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/GROUNDCREATURE/ENTITIES/WEIRDDIGGER.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/GROUNDCREATURE/ENTITIES/DRILL.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/DIGGER/ENTITIES/DIGGER.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/WEIRDBUTTERFLY/ENTITIES/WEIRDBUTTERFLY.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

#!mbinFile MODELS/PLANETS/CREATURES/WEIRD/ROLLERCREATURE/ENTITIES/_STRANGE_ROLL.ENTITY.MBIN
#!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/WEIRDFLOCK/ENTITIES/WEIRDFLOCK.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/PLOW/ENTITIES/PLOW.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SPIDERRIG/SPIDER/ENTITIES/_ACC1_BULBTOP.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SPIDERRIG/FREIGHTERFIEND/ENTITIES/FREIGHTERFIEND.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SPIDERRIG/ROCKCREATURE/ENTITIES/ROCKCREATURE.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SPIDERRIG/ROCKSPIDER/ENTITIES/ROCKSPIDER.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SANDWORM/SANDWORM/ENTITIES/SANDWORM.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLY/ENTITIES/JELLYFISH.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLY/ENTITIES/BUTTERFLY.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/BUTTERFLYRIG/BUTTERFLYFLOCK/ENTITIES/BUTTERFLYFLOCK.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

#!mbinFile MODELS/PLANETS/CREATURES/BUTTERFLYRIG/LARGEBUTTERFLY/ENTITIES/LARGEBUTTERFLYDATA.ENTITY.MBIN
#!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/RODENTRIG/RODENTSWIM/ENTITIES/RODENTSWIM.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/COWRIG/COWSWIM/ENTITIES/_COW_SWIM.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FISH/JELLYFISH/ENTITIES/JELLYFISH.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FISH/ASTEROIDJELLYFISH/ENTITIES/ASTEROIDJELLYFISH.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FISH/FISHFIEND/ENTITIES/FISHFIEND.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FISH/FISHFLOCK/ENTITIES/FISHFLOCK.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FISH/FREIGHTERJELLYFISH/ENTITIES/FREIGHTERJELLYFISH.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FISH/SMALLFISH/ENTITIES/BIGFISH.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FISH/SMALLFISH/ENTITIES/SMALLFISH.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/FISH/PROC_JELLYFISH/ENTITIES/PROCJELLYFISH.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

#!mbinFile MODELS/PLANETS/CREATURES/BEETLERIG/BEETLE/ENTITIES/BEETLEDATA.ENTITY.MBIN
#!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/SEASNAKE/SEASNAKE/ENTITIES/SEASNAKE.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/CAVE/SMALLCREATURE/SUNBEETLE/SUNBEETLE/ENTITIES/SUNBEETLE.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMCREATURE/ANTELOPE/ANTELOPE/ENTITIES/ANTELOPE3.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/MEDIUMCREATURE/ANTELOPE/ANTELOPEFAKE/ENTITIES/ANTELOPEFAKE.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/TRICERATOPS/TRICERATOPSTWOHEADS/ENTITIES/_BODY_TRI.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/TRICERATOPS/TRICERATOPS/ENTITIES/_BODY_TRI.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/TRICERATOPS/QUADREPTILE/ENTITIES/_BODY_TRI.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/RHINO/RHINOSTANDARD/ENTITIES/_BODY_RHINOSTANDARD.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/RHINO/RHINO/ENTITIES/_BODY_RHINO.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/RHINO/RHINO02/ENTITIES/_BODY_RHINO.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/FLYINGLIZARD/FLYINGLIZARDPATH/ENTITIES/FLYINGLIZARD.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/FLYINGLIZARD/FLYINGLIZARD/ENTITIES/FLYINGLIZARD.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/LARGECREATURE/DIPLODOCUS/DIPLODOCUS/ENTITIES/DIPLO.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/SMALLCREATURE/BUTTERFLY/GLOWBUG/ENTITIES/GLOWBUG.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/SMALLCREATURE/BUTTERFLY/BUTTERFLY/ENTITIES/BUTTERFLY.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/BIOMES/RAINFOREST/SMALLCREATURE/RODENT/RODENT/ENTITIES/_BODY_RODENT.ENTITY.MBIN
!include CompanionPetUnlocker_InteractionAction.inc

!mbinFile MODELS/PLANETS/CREATURES/BEETLERIG/BEETLE/ENTITIES/BEETLEDATA.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
RepeatInteraction=False
UseInteractCamera=False

!mbinFile MODELS/PLANETS/CREATURES/BUTTERFLYRIG/LARGEBUTTERFLY/ENTITIES/LARGEBUTTERFLYDATA.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
RepeatInteraction=False
UseInteractCamera=False

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/ROLLERCREATURE/ENTITIES/_STRANGE_ROLL.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
RepeatInteraction=False
UseInteractCamera=False

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIG/ENTITIES/WEIRDFLOAT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
RepeatInteraction=False
UseInteractCamera=False

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIG/ENTITIES/WEIRDROLL.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
RepeatInteraction=False
UseInteractCamera=False


!mbinFile MODELS/COMMON/ROBOTS/QUADRUPED/ENTITIES/QUADRUPED_MESH.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/COMMON/ROBOTS/QUADRUPED/ENTITIES/QUADRUPED_PET.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/COMMON/ROBOTS/SPHEREDRONE/ENTITIES/DRONEJNT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/COMMON/ROBOTS/SPIDER_QUADRUPED/ENTITIES/SPIDERQUAD.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/COMMON/ROBOTS/SPIDER_SMALLQUAD/ENTITIES/SPIDERSMALLQUAD.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPE/ENTITIES/_BODY_CYBER1.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPE/ENTITIES/_BODY_SKINNY.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/BEETLERIG/BEETLE/ENTITIES/BEETLEDATA.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPEROBOT/ENTITIES/ANTELOPEROBOT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/ANTELOPERIG/ANTELOPETWOLEGS/ENTITIES/_BODY_TWOLEGDEER1.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/BLOBRIG/BLOB/ENTITIES/_BODY_BLOB.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/BUTTERFLYRIG/LARGEBUTTERFLY/ENTITIES/LARGEBUTTERFLYDATA.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/CATRIG/BONECAT/ENTITIES/BONECATBODY.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/CATRIG/CAT/ENTITIES/CATHINDLEGS.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/CATRIG/CAT/ENTITIES/CAT_BODY.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/CATRIG/SIXLEGCAT/ENTITIES/_BODY_SIXLEGCAT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/COWRIG/COWFLOATING/ENTITIES/_BODY_ROCK.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/COWRIG/COW/ENTITIES/_BODY_COW.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/COWRIG/COWHINDLEGS/ENTITIES/_BODY_ROCK.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/COWRIG/SIXLEGGEDCOW/ENTITIES/_BODY_6LEGCOW.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/FISH/LANDJELLYFISH/ENTITIES/LANDJELLYFISH.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile #MODELS/PLANETS/CREATURES/FLYINGLIZARDRIG/FLYINGLIZARD/ENTITIES/BODY_LIZARD.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile #MODELS/PLANETS/CREATURES/FLYINGSNAKE/FLYINGSNAKE/ENTITIES/KITECREATURE.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/GRUNTRIG/GRUNT/ENTITIES/_BODY_GRUNTFLOAT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/GRUNTRIG/GRUNT/ENTITIES/_BODY_GRUNT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/RODENTRIG/RODENT/ENTITIES/_BODY_RODENT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/SPIDERRIG/FIEND/ENTITIES/_FIEND_BODY.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/SPIDERRIG/SPIDER/ENTITIES/SPIDERFLOAT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/SPIDERRIG/SPIDER/ENTITIES/SPIDER.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/STRIDERRIG/STRIDER/ENTITIES/STRIDERMESH.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/TREXRIG/TREX/ENTITIES/_BODY_TREX.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/TRICERATOPSRIG/TRICERATOPS/ENTITIES/_BODY_TRI.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/FLOATERCREATURE/ENTITIES/_STRANGE_FLOAT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/ROLLERCREATURE/ENTITIES/_STRANGE_ROLL.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIG/ENTITIES/WEIRDFLOAT.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100

!mbinFile MODELS/PLANETS/CREATURES/WEIRD/WEIRDRIG/ENTITIES/WEIRDROLL.ENTITY.MBIN
cd /Components/=GcInteractionComponentData.xml
InteractDistance=100



!mbinFile MODELS/PLANETS/BIOMES/COMMON/INTERACTIVE/PET_EGG/ENTITIES/PET_EGG.ENTITY.MBIN
cd /Components/=GcSimpleInteractionComponentData.xml/Id[=R_PETEGGLOOT]/..
InteractDistance=25



!mbinFile METADATA/SIMULATION/ECOSYSTEM/CREATUREDATATABLE.MBIN

### FISH
cd /Table/=GcCreatureData.xml/Id[=FISH]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=FISH]/../Data/=GcCreatureRidingData.xml
JointName=joint1
!include CompanionPetUnlocker_JointCommon.inc

### FISHFLOCK
cd /Table/=GcCreatureData.xml/Id[=FISHFLOCK]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=FISHFLOCK]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### SWIMCOW
cd /Table/=GcCreatureData.xml/Id[=SWIMCOW]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=SWIMCOW]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### SWIMRODENT
cd /Table/=GcCreatureData.xml/Id[=SWIMRODENT]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=SWIMRODENT]/../Data/=GcCreatureRidingData.xml
JointName=GlobalJNT
!include CompanionPetUnlocker_JointCommon.inc

### JELLYFISH
cd /Table/=GcCreatureData.xml/Id[=JELLYFISH]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=JELLYFISH]/../Data/=GcCreatureRidingData.xml
JointName=centre
!include CompanionPetUnlocker_JointCommon.inc

### SEASNAKE
cd /Table/=GcCreatureData.xml/Id[=SEASNAKE]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=SEASNAKE]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### SHARK
cd /Table/=GcCreatureData.xml/Id[=SHARK]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=SHARK]/../Data/=GcCreatureRidingData.xml
JointName=Root
!include CompanionPetUnlocker_JointCommon.inc

### BIRD
cd /Table/=GcCreatureData.xml/Id[=BIRD]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=BIRD]/../Data/=GcCreatureRidingData.xml
JointName=Root
!include CompanionPetUnlocker_JointCommon.inc

### FLYINGSNAKE
#cd /Table/=GcCreatureData.xml/Id[=FLYINGSNAKE]/../Data
#=GcCreatureRidingData.xml
#cd /Table/=GcCreatureData.xml/Id[=FLYINGSNAKE]/../Data/=GcCreatureRidingData.xml
#JointName=RootJNT
#!include CompanionPetUnlocker_JointCommon.inc

### FLYINGLIZARD
#cd /Table/=GcCreatureData.xml/Id[=FLYINGLIZARD]/../Data
#=GcCreatureRidingData.xml
#cd /Table/=GcCreatureData.xml/Id[=FLYINGLIZARD]/../Data/=GcCreatureRidingData.xml
#JointName=Back2JNT
#!include CompanionPetUnlocker_JointCommon.inc

### BUTTERFLY
cd /Table/=GcCreatureData.xml/Id[=BUTTERFLY]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=BUTTERFLY]/../Data/=GcCreatureRidingData.xml
JointName=Root
!include CompanionPetUnlocker_JointCommon.inc

### SMALLBIRD
cd /Table/=GcCreatureData.xml/Id[=SMALLBIRD]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=SMALLBIRD]/../Data/=GcCreatureRidingData.xml
JointName=Root
!include CompanionPetUnlocker_JointCommon.inc

### BUTTERFLOCK
cd /Table/=GcCreatureData.xml/Id[=BUTTERFLOCK]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=BUTTERFLOCK]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### MOLE
cd /Table/=GcCreatureData.xml/Id[=MOLE]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=MOLE]/../Data/=GcCreatureRidingData.xml
JointName=DiggerROOT
!include CompanionPetUnlocker_JointCommon.inc

### PROTOROLLER
cd /Table/=GcCreatureData.xml/Id[=PROTOROLLER]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=PROTOROLLER]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### PROTODIGGER
cd /Table/=GcCreatureData.xml/Id[=PROTODIGGER]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=PROTODIGGER]/../Data/=GcCreatureRidingData.xml
JointName=EyeStalkROOT
!include CompanionPetUnlocker_JointCommon.inc

### PLOUGH
cd /Table/=GcCreatureData.xml/Id[=PLOUGH]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=PLOUGH]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### DRILL
cd /Table/=GcCreatureData.xml/Id[=DRILL]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=DRILL]/../Data/=GcCreatureRidingData.xml
JointName=DiggerROOT
!include CompanionPetUnlocker_JointCommon.inc

### WEIRDROLL
cd /Table/=GcCreatureData.xml/Id[=WEIRDROLL]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=WEIRDROLL]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### WEIRDFLOAT
cd /Table/=GcCreatureData.xml/Id[=WEIRDFLOAT]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=WEIRDFLOAT]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### WEIRDCRYSTAL
cd /Table/=GcCreatureData.xml/Id[=WEIRDCRYSTAL]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=WEIRDCRYSTAL]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### WEIRDBUTTERFLY
cd /Table/=GcCreatureData.xml/Id[=WEIRDBUTTERFLY]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=WEIRDBUTTERFLY]/../Data/=GcCreatureRidingData.xml
JointName=shellfly_ROOTSHJnt
!include CompanionPetUnlocker_JointCommon.inc

### FIEND
#cd /Table/=GcCreatureData.xml/Id[=FIEND]/../Data
#=GcCreatureRidingData.xml
#cd /Table/=GcCreatureData.xml/Id[=FIEND]/../Data/=GcCreatureRidingData.xml
#JointName=RootJNT
#!include CompanionPetUnlocker_JointCommon.inc

### SCUTTLER
cd /Table/=GcCreatureData.xml/Id[=SCUTTLER]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=SCUTTLER]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### SLUG
cd /Table/=GcCreatureData.xml/Id[=SLUG]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=SLUG]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### MINIFIEND
cd /Table/=GcCreatureData.xml/Id[=MINIFIEND]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=MINIFIEND]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### FIENDFISHSMALL
cd /Table/=GcCreatureData.xml/Id[=FIENDFISHSMALL]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=FIENDFISHSMALL]/../Data/=GcCreatureRidingData.xml
JointName=joint1
!include CompanionPetUnlocker_JointCommon.inc

### FLOATER
cd /Table/=GcCreatureData.xml/Id[=FLOATER]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=FLOATER]/../Data/=GcCreatureRidingData.xml
JointName=FrontJNT
!include CompanionPetUnlocker_JointCommon.inc

### MINIDRONE
cd /Table/=GcCreatureData.xml/Id[=MINIDRONE]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=MINIDRONE]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc

### FIENDFISHBIG
cd /Table/=GcCreatureData.xml/Id[=FIENDFISHBIG]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=FIENDFISHBIG]/../Data/=GcCreatureRidingData.xml
JointName=joint1
!include CompanionPetUnlocker_JointCommon.inc

### ROCKCREATURE
cd /Table/=GcCreatureData.xml/Id[=ROCKCREATURE]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=ROCKCREATURE]/../Data/=GcCreatureRidingData.xml
JointName=RootJNT
!include CompanionPetUnlocker_JointCommon.inc


### LARGEBUTTERFLY
cd /Table/=GcCreatureData.xml/Id[=LARGEBUTTERFLY]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=LARGEBUTTERFLY]/../Data/=GcCreatureRidingData.xml

Offset=Vector3f.xml
cd Offset
y=0.25
z=-0.125
cd ..

UprightStrength=1
ScaleForNeutralLegSpread=1.25
ScaleForMinLegSpread=0.5
ScaleForMaxLegSpread=4.75


!mbinFile METADATA/SIMULATION/ECOSYSTEM/ROBOTDATATABLE.MBIN

cd /Table/=GcCreatureData.xml/Id[=WALKER]/../Data
=GcCreatureRidingData.xml
cd /Table/=GcCreatureData.xml/Id[=WALKER]/../Data/=GcCreatureRidingData.xml
JointName=Root
AdditionalScaleJoint=
Offset=Vector3f.xml

cd /Table/=GcCreatureData.xml/Id[=WALKER]/../Data/=GcCreatureRidingData.xml/Offset
x=0
y=0.25
z=-0.125

cd /Table/=GcCreatureData.xml/Id[=WALKER]/../Data/=GcCreatureRidingData.xml
RotationOffset=Vector3f.xml

cd /Table/=GcCreatureData.xml/Id[=WALKER]/../Data/=GcCreatureRidingData.xml/RotationOffset
x=0
y=0
z=0

cd /Table/=GcCreatureData.xml/Id[=WALKER]/../Data/=GcCreatureRidingData.xml
VROffset=Vector3f.xml

cd /Table/=GcCreatureData.xml/Id[=WALKER]/../Data/=GcCreatureRidingData.xml/VROffset
x=0
y=0
z=0

cd /Table/=GcCreatureData.xml/Id[=WALKER]/../Data/=GcCreatureRidingData.xml
HeadCounterRotation=0
UprightStrength=1
LegSpread=True
ScaleForNeutralLegSpread=1.25
ScaleForMinLegSpread=0.5
ScaleForMaxLegSpread=4.75
RequiresMatchingPartModifier=False
PartModifiers
IdleRidingAnim=RIDE_ANT_IDLE
DefaultRidingAnim=RIDE_ANT_WALK
RidingAnims

cd /Table/=GcCreatureData.xml/Id[=QUAD]/../Data/=GcCreatureRidingData.xml
LegSpread=True
ScaleForNeutralLegSpread=1.25
ScaleForMinLegSpread=0.5
ScaleForMaxLegSpread=4.75
IdleRidingAnim=RIDE_ANT_IDLE
DefaultRidingAnim=RIDE_ANT_WALK

######################
### NMSARC.globals.pak

!inputPakFile NMSARC.globals.pak
!mbinFile GCCREATUREGLOBALS.MBIN

cd /

CreatureInteractionRangeBoostHuge=3
CreatureInteractionRangeBoostLarge=2.4
CreatureInteractionRangeBoostMedium=2.2
CreatureInteractionRangeBoostSmall=2
CreatureInteractionRangeBoostRun=4
CreatureInteractionRangeBoostSprint=7
CreatureInteractionRangeReducePredator=0.6
CreatureInteractBaseRange=750
PetInteractBaseRange=1200

MinRideSize=0.1
AllowSleeping=True
AggressiveSharks=False
PiedPiper=False

LowPerfFlockReduce=0.5

PetGrowthTime=0
PetIncubationTime=0
PetTrustChangeInterval=0
PetTrustOnAdoption=1
PetTrustOnHatch=1
PetMinTrust=1
PetEggLayingDuration=0
PetEggLayingInterval=0
PetEggFirstEggDelay=0
PetEggModificationTime=1

CanAlwaysLayEgg=True

# more creatures
PauseBetweenCreatureSpawnRequests=200
CreatureUpdateRateMultiplier=4
