AdditionalScaleJoint=

Offset=Vector3f.xml
cd Offset
x=0
y=0.25
z=-0.125
cd ..

RotationOffset=Vector3f.xml
cd RotationOffset
x=0
y=0
z=0
cd ..

VROffset=Vector3f.xml
cd VROffset
x=0
y=0
z=0
cd ..

HeadCounterRotation=0
UprightStrength=1
LegSpread=True
ScaleForNeutralLegSpread=1.25
ScaleForMinLegSpread=0.5
ScaleForMaxLegSpread=4.75
RequiresMatchingPartModifier=False
PartModifiers
IdleRidingAnim=RIDE_ANT_IDLE
DefaultRidingAnim=RIDE_ANT_WALK
RidingAnims
