name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build for Linux
        run: |
          mkdir build-linux
          cd build-linux
          cmake ..
          make

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-linux
          path: build-linux/nmsmc

  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up MinGW toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64
          echo "CC=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV
          echo "CXX=x86_64-w64-mingw32-g++" >> $GITHUB_ENV

      - name: Install libxml2 library
        run: |
          sudo apt-get install -y autopoint gettext
          wget http://xmlsoft.org/download/libxml2-2.9.12.tar.gz
          tar -zxvf libxml2-2.9.12.tar.gz
          cd libxml2-2.9.12
          autoreconf -i
          ./configure --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32 --without-lzma
          make
          sudo make install

      - name: Build for Windows
        run: |
          mkdir build-windows
          cd build-windows
          cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/Toolchain-cross-mingw.cmake ..
          make

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-windows
          path: build-windows/nmsmc.exe
                libxml2-2.9.12/.libs/libxml2-2.dll

  release:
    runs-on: ubuntu-latest
    needs: [build, build-windows]

    steps:
      - name: Download files for release
        uses: actions/download-artifact@v3

      - name: Create Release and Upload Binaries
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build-linux/nmsmc
            build-windows/nmsmc.exe
            libxml2-2.9.12/.libs/libxml2-2.dll
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
